require 'colorize'

output = ''
output += '8 '
output += '♜ '.on_grey
output += '♞ '.on_magenta
output += '♝ '.on_grey
output += '♛ '.on_magenta
output += '♚ '.on_grey
output += '♝ '.on_magenta
output += '♜ '.on_grey
output += '♞ '.on_magenta
output += "\n"
output += '7 '
output += '♟︎ '.on_magenta
output += '♟︎ '.on_grey
output += '♟︎ '.on_magenta
output += '♟︎ '.on_grey
output += '♟︎ '.on_magenta
output += '♟︎ '.on_grey
output += '♟︎ '.on_magenta
output += '♟︎ '.on_grey
output += "\n"
output += '6 '
output += '  '.on_grey
output += '  '.on_magenta
output += '  '.on_grey
output += '  '.on_magenta
output += '  '.on_grey
output += '  '.on_magenta
output += '  '.on_grey
output += '  '.on_magenta
output += "\n"
output += '5 '
output += '  '.on_magenta
output += '  '.on_grey
output += '  '.on_magenta
output += '  '.on_grey
output += '  '.on_magenta
output += '  '.on_grey
output += '  '.on_magenta
output += '  '.on_grey
output += "\n"
output += '4 '
output += '  '.on_grey
output += '  '.on_magenta
output += '  '.on_grey
output += '  '.on_magenta
output += '  '.on_grey
output += '  '.on_magenta
output += '  '.on_grey
output += '  '.on_magenta
output += "\n"
output += '3 '
output += '  '.on_magenta
output += '  '.on_grey
output += '  '.on_magenta
output += '  '.on_grey
output += '  '.on_magenta
output += '  '.on_grey
output += '  '.on_magenta
output += '  '.on_grey
output += "\n"
output += '2 '
output += '♙ '.on_grey
output += '♙ '.on_magenta
output += '♙ '.on_grey
output += '♙ '.on_magenta
output += '♙ '.on_grey
output += '♙ '.on_magenta
output += '♙ '.on_grey
output += '♙ '.on_magenta
output += "\n"
output += '1 '
output += '♖ '.on_magenta
output += '♘ '.on_grey
output += '♗ '.on_magenta
output += '♕ '.on_grey
output += '♔ '.on_magenta
output += '♗ '.on_grey
output += '♘ '.on_magenta
output += '♖ '.on_grey
output += "\n"
output += '  a b c d e f g h'

puts output
