# frozen_string_literal: true

require_relative 'game_board'
require_relative 'legal_moves'
require_relative 'legal_castling'

describe GameBoard do
  castling = %w[
    r...k..r
    ........
    ........
    ........
    ........
    ........
    ........
    ........
  ]

  subject { described_class.new(castling) }
  describe '#path_clear?' do
  end
end
